--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: myfirstproject
    version: v1
  name: myfirstproject
spec: 
  strategy: # Default, so usually not specified
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # specifies the maximum number of Pods that can be created over the desired number of Pods
      maxUnavailable: 25% #specifies the maximum number of Pods that can be unavailable during the update process
  replicas: 1
  selector: 
    matchLabels: 
      app: myfirstproject
      version: v1
  template: 
    metadata: 
      labels: 
        app: myfirstproject
        version: v1

    spec: 

      containers: 
        - 
          image: "newtonmn/firstservicev1:latest"
          imagePullPolicy: Always
          name: myfirstproject

                          