spring:
  datasource:
    url: jdbc:h2:mem:productdb
    driver-class-name: org.h2.Driver
    username: ibm
    password: ibm
     h2:    console:      enabled: true  application:    name: product-service
      
server:  port: 8085
  
  
management:  endpoints:    web:      exposure:        include: "*"       
eureka:  instance:    instance-id: ${spring.application.name}:${random.int}
    
  client:    service-url:      defaultZone:  http://localhost:8100/eureka