spring:
   zipkin:    base-url: http://192.168.99.100:9411  sleuth:    sampler:      probability: 1.0
    trace-id128: true
      
server:  port: 8088
  
  
management:  endpoints:    web:      exposure:        include: "*"       

      
      
      