server:
  port: 8200
  
spring:  application:    name: api-gateway
      cloud:    gateway:      routes:      - id: productService
        uri: lb://product-service
        predicates:        - Path=/product/**              - id: taxService
        uri: lb://tax-service
        predicates:
        - Path=/tax/**   
    
   
    
    
    
    
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    
  client:
    service-url:
      defaultZone:  http://localhost:8100/eureka