--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: configserver
    version: v1
  name: configserver
spec: 
  ports: 
    - 
      name: http
      port: 8110
      targetPort: 8110
  selector: 
    app: configserver
    version: v1
  type: NodePort